let result = document.getElementById('result');

const DareList =[
    "Sing the chorus of your favorite song loudly.",
    "Dance with no music for 1 minute.",
    "Eat a spoonful of hot sauce.",
    "Let someone draw on your face with a marker.",
    "Wear socks on your hands for the next 10 minutes.",
    "Speak in an accent for the next 3 rounds.",
    "Do 20 push-ups.",
    "Do an impression of your favorite celebrity.",
    "Post an embarrassing photo on social media.",
    "Let the person to your right text anyone from your phone.",
    "Attempt to juggle 3 items of the group's choice.",
    "Wear your clothes backward for the next hour.",
    "Do a handstand for as long as you can.",
    "Imitate a famous movie scene until someone guesses it.",
    "Let someone tickle you for 30 seconds.",
    "Do your best chicken dance outside on the lawn.",
    "Exchange an item of clothing with the person on your left.",
    "Eat a raw onion slice.",
    "Speak only in questions until your next turn.",
    "Let the group give you a new hairstyle.",
    "Let someone write a word on your forehead in a permanent marker.",
    "Act like a monkey until it's your turn again.",
    "Do your best moonwalk.",
    "Send a romantic message to a random contact in your phone.",
    "Let the group give you a nickname and use it for the rest of the game.",
    "Put an ice cube down your shirt and wait until it melts.",
    "Do your best animal impression.",
    "Walk around the room while balancing a book on your head.",
    "Do 30 jumping jacks.",
    "Talk in a high-pitched voice until your next turn.",
    "Let someone paint your nails any color they choose.",
    "Hold a funny face for the next 2 minutes.",
    "Say the alphabet backwards as fast as you can.",
    "Let someone else redo your makeup.",
    "Wear a silly hat for the next 3 rounds.",
    "Make up a poem on the spot.",
    "Try to lick your elbow.",
    "Let someone write a dare on your arm with a permanent marker.",
    "Dance like a ballerina until your next turn.",
    "Try to touch your nose with your tongue.",
    "Wear a blindfold and let someone feed you something.",
    "Speak in a whisper until your next turn.",
    "Pretend to be a waiter/waitress and take snack orders from everyone in the group.",
    "Do a silly walk across the room.",
    "Let someone give you a back massage for 2 minutes.",
    "Let someone draw a mustache on your face.",
    "Stand on one foot for the next 3 rounds.",
    "Let someone style your hair in a ridiculous way.",
    "Try to keep a straight face while the group makes funny faces at you."
  
  ];
const TruthList  =[
    "What is your most embarrassing moment?",
    "What is the biggest lie you've ever told?",
    "Have you ever had a crush on a teacher?",
    "What is the most childish thing you still do?",
    "What is the last thing you searched for on your phone?",
    "Have you ever cheated on a test?",
    "If you could switch lives with someone for a day, who would it be?",
    "What is your biggest fear?",
    "What is your biggest insecurity?",
    "Have you ever had a crush on someone in this room?",
    "What is the most illegal thing you have ever done?",
    "What is the biggest secret you’ve kept from your parents?",
    "Have you ever lied to get out of a bad date?",
    "What is the most embarrassing thing in your room?",
    "Have you ever been caught doing something you shouldn't have?",
    "What is your worst habit?",
    "What is the most trouble you’ve gotten into at school?",
    "What is the silliest thing you have an emotional attachment to?",
    "What is your guilty pleasure?",
    "What is the longest you have gone without showering?",
    "What is the weirdest dream you have ever had?",
    "Have you ever pretended to be sick to get out of something?",
    "What is the most embarrassing thing you’ve posted on social media?",
    "What is the one thing you would never want your parents to find out about you?",
    "Have you ever had a romantic encounter in public?",
    "What is your biggest regret?",
    "Who is the last person you stalked on social media?",
    "What is the most awkward date you’ve been on?",
    "Have you ever been rejected by someone?",
    "What is the most childish thing you still do?",
    "What is something you’ve never told anyone?",
    "What is the most awkward thing that happened to you in a public place?",
    "What is the weirdest thing you do when you’re alone?",
    "What is the strangest thing you have in your room?",
    "Have you ever lied about your age?",
    "What is the most embarrassing nickname you’ve ever had?",
    "Have you ever been caught sneaking out?",
    "What is your least favorite thing about your best friend?",
    "What is the meanest thing you’ve ever said to someone?",
    "Have you ever ghosted someone?",
    "What is the craziest thing you have done while drunk?",
    "What is the most embarrassing song on your playlist?",
    "What is the weirdest thing you’ve ever eaten?",
    "Have you ever stolen something?",
    "What is the most awkward conversation you’ve had?",
    "What is your most unusual talent?",
    "Have you ever had a crush on a friend's partner?",
    "What is the worst date you’ve ever been on?",
    "Have you ever lied in a truth or dare game?"
  ];
function truthchoice(){
    let random = Math.floor(Math.random()*49);
    result.textContent = TruthList[random];
    result.style.color = "blue";
}
function darechoice(){
    let random = Math.floor(Math.random()*49);
    result.textContent = DareList[random];
    result.style.color = "red";
}